apiVersion: v1
kind: Secret
metadata:
  name: sqlbot-secret
  namespace: sqlbot
  labels:
    app.kubernetes.io/name: sqlbot
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Password123@pg"
  SECRET_KEY: "y5txe1mRmS_JpOrUzFzHEu-kIQn3lf7ll0AOv9DQh0s"
