# SQLBot Spring Boot Starter 默认配置示例
# 用户可以在自己的application.yml中覆盖这些配置

sqlbot:
  # 是否启用SQLBot功能（默认：true）
  enabled: true
  
  # SQLBot服务器地址
  url: http://localhost:8000/api/v1
  # 用户认证信息（请在实际环境中配置）
  username: admin
  password: SQLBot@123456
  
  # 超时配置（单位：毫秒）
  timeout: 30000              # 请求超时时间
  connection-timeout: 10000   # 连接超时时间
  read-timeout: 30000         # 读取超时时间
  
  # 重试配置
  max-retries: 3              # 最大重试次数
  
  # OkHttp连接池配置（高级配置）
  okhttp:
    max-idle-connections: 5     # 最大空闲连接数
    keep-alive-duration: 300    # 连接保活时间（秒）
    connection-pool-size: 10    # 连接池大小

# 日志配置（可选）
logging:
  level:
    com.sqlbot.springboot.starter: DEBUG
    root: INFO