# Spring Boot 2.x SQLBot示例项目配置
server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: sqlbot-springboot-example
  
  # 日志配置
  logging:
    level:
      # 应用包日志级别
      com.sqlbot: DEBUG
      com.sqlbot.example: DEBUG
      # SQLBot Starter 日志级别
      com.sqlbot.springboot.starter: DEBUG
      # HTTP请求日志
      okhttp3: DEBUG
      # Spring框架日志
      org.springframework.web: DEBUG
      org.springframework.web.servlet: DEBUG
    pattern:
      # 控制台日志格式
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      # 文件日志格式
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file:
      # 日志文件路径
      name: logs/sqlbot-example.log
      # 日志文件大小限制
      max-size: 100MB
      # 日志文件保留天数
      max-history: 30

# SQLBot配置
sqlbot:
  # 服务器地址
  url: http://127.0.0.1:8000/api/v1
  # 连接超时时间（毫秒）
  connection-timeout: 10000
  # 读取超时时间（毫秒）
  read-timeout: 30000
  # 写入超时时间（毫秒）
  timeout: 30000
  # 最大重试次数
  max-retries: 3

# 应用信息
app:
  name: SQLBot SpringBoot Example
  version: 1.0.0
  description: SQLBot SpringBoot集成示例应用

