# 开发环境配置
server:
  port: 8080

spring:
  profiles:
    active: dev

sqlbot:
  url: http://localhost:8000
  username: dev_user
  password: dev_password
  debug: true

logging:
  level:
    com.sqlbot: DEBUG
    org.springframework.web: DEBUG
