server:
  port: 8081

spring:
  application:
    name: sqlbot-springboot3-example
  
  # Thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

# SQLBot配置
sqlbot:
  enabled: true
  url: http://localhost:8000
  username: test
  password: test123
  timeout: 30000
  max-retries: 3
  connection-timeout: 10000
  read-timeout: 30000

# 日志配置
logging:
  level:
    com.sqlbot: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
