apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlbot.fullname" . }}
  labels:
    {{- include "sqlbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "sqlbot.selectorLabels" . | nindent 4 }}
